options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Deploy generate
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'generate-audiobook', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'generate', '--memory', '1024MB', '--region', 'europe-central2'
  ]

# Deploy delete
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'delete-audiobook', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'delete', '--memory', '512MB', '--region', 'europe-central2'
  ]

# Deploy add-chapter
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'add-chapter', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'add-chapter', '--memory', '1024MB', '--region', 'europe-central2'
  ]

# Deploy export
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'export', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './export',
    '--entry-point', 'exportAudiobook', '--memory', '512MB', '--region', 'europe-west2'
  ]

# Deploy export video
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'exportAudiobookVideo', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './export',
    '--entry-point', 'exportAudiobookVideo', '--memory', '4096MB', '--region', 'europe-west2'
  ]

# Deploy manageTemplate
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'manageTemplate', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'manageTemplate', '--memory', '256MB', '--region', 'europe-central2'
  ]

  # Deploy getTemplates
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'getTemplates', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'getTemplates', '--memory', '256MB', '--region', 'europe-central2'
  ]

  # Deploy createVoice
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'createVoice', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'createVoice', '--memory', '256MB', '--region', 'europe-central2'
  ]

  # Deploy saveVoice
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'saveVoice', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'saveVoice', '--memory', '256MB', '--region', 'europe-central2'
  ]

  # Deploy listVoices
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'listVoices', 
    '--trigger-http', '--gen2', '--runtime', 'nodejs20', '--source', './backend',
    '--entry-point', 'listVoices', '--memory', '256MB', '--region', 'europe-central2'
  ]

timeout: '1600s' # Adjust the timeout to your needs
