steps:
# Deploy Function1
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'add-chapter', '--trigger-http', '--runtime', 'nodejs18', '--source', '.']


timeout: '1600s' # Adjust the timeout to your needs